name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Poetry
        run: pip install poetry
      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: '96.0.4664.45'
      - name: Install dependencies
        run: poetry install
      - name: Run e2e tests
        run: bash run_e2e_tests.sh
      - name: Archive e2e test report
        uses: actions/upload-artifact@v2
        with:
          name: e2e-test-report
          path: report.html
